# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking
        - !!!
    - title: FEATURE
      labels:
        - Semver-Minor
        - feature
    - title: TASK
      labels:
        - Semver-Minor
        - task
    - title: BUGFIX
      labels:
        - Semver-Minor
        - bugfix
    - title: Other Changes
      labels:
        - "*"
