# We want to adjust this to pnp at some point to enforce strict dependency checks,
# currently this would break everything as the dependencies are incomplete in most packages.
nodeLinker: pnp
pnpMode: strict

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

# in combination with isemail-npm-3.2.0-browserified.patch
# https://github.com/neos/neos-ui/pull/3200#issuecomment-1284419262
packageExtensions:
  "isemail@3.2.0":
    dependencies:
      "buffer": "^5.0.0"
  "react-dnd@*":
    dependencies:
      "@react-dnd/invariant": "2.0.0"
  "@neos-project/positional-array-sorter@*":
    dependencies:
      "tslib": "^2.1.0"
  "@ckeditor/ckeditor5-alignment@*":
    dependencies:
      "@ckeditor/ckeditor5-utils": "^16.0.0"
  "@ckeditor/ckeditor5-table@*":
    dependencies:
      "@ckeditor/ckeditor5-utils": "^16.0.0"
  "@ckeditor/ckeditor5-link@*":
    dependencies:
      "@ckeditor/ckeditor5-utils": "^16.0.0"
  "@ckeditor/ckeditor5-core@*":
    dependencies:
      "@ckeditor/ckeditor5-ui": "^16.0.0"
  "ts-jest@*":
    dependencies:
      "resolve": "^1.9.0"
  "tslint@*":
    dependencies:
      "resolve": "^1.9.0"
  "rechoir@*":
    dependencies:
      "resolve": "^1.9.0"
  "postcss-import@*":
    dependencies:
      "resolve": "^1.9.0"

# Needed for the yarn version comparison
changesetBaseRefs:
  - origin/8.2
  - composer/8.2

# NPM publish config
npmAlwaysAuth: true
npmAuthToken: "${NPM_TOKEN}"
npmPublishAccess: "public"
